name: Test Workflow

on:
  push:
    branches: [ main ] # Trigger the workflow on push events to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3 # Action to checkout the repository

    - name: Find .csproj file
      run: |
        project_dir=$(find . -maxdepth 1 -type d -name "*.[cp]proj")
        if [[ -z "$project_dir" ]]; then
          echo "Error: No .csproj file found"
          exit 1
        fi
        echo $project_dir
      shell: bash
