name: Test Workflow

on:
  push:
    branches: [ main ] # Trigger the workflow on push events to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3 # Action to checkout the repository

    - name: Find .csproj file
      id: find-project
      run: |
        project_dir=$(dirname $(find . -type f -name "*.csproj" | head -n 1))
        if [[ -z "$project_dir" ]]; then
          echo "Error: No .csproj file found"
          exit 1
        fi
        echo $project_dir
        echo "project_dir=$project_dir" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Build
      working-directory: ${{ steps.find-project.outputs.project_dir }}
      run: |
        echo "Project Directory: ${{ steps.find-project.outputs.project_dir }}"
        dotnet restore
        dotnet publish -p:UseAppHost=False -p:MapFileExtensions=False -c Debug -o ./output
        
    - name: Create zip archive
      working-directory: ${{ steps.find-project.outputs.project_dir }}
      run: zip -r veracode.zip ./output

    - uses: actions/upload-artifact@v3
      with:
        name: veracode-artifact
        path: veracode.zip
